'use client';

import { useContext } from 'react';
import { ArrowRight, BriefcaseBusiness, FileText, Lightbulb, Mic, ShieldCheck, Sparkles, Target } from 'lucide-react';
import { ModalContext } from '@/contexts/LoginModalContext';

const jobs = [
  ['S', 'Senior Product Designer', 'Stripe · Remote', '96% match'],
  ['V', 'Product Designer', 'Vercel · New York', '91% match'],
  ['L', 'UX Designer', 'Linear · Remote', '89% match'],
];

const features = [
  { icon: Target, title: 'Smart job matching', text: 'See opportunities ranked by the skills, goals, and working style that matter to you.', tone: 'bg-violet-50 text-violet-600' },
  { icon: FileText, title: 'Tailored resumes', text: 'Build ATS-ready resumes that highlight the work each role is really looking for.', tone: 'bg-blue-50 text-blue-600' },
  { icon: Mic, title: 'Interview practice', text: 'Practice aloud, get thoughtful feedback, and turn nerves into a clear story.', tone: 'bg-emerald-50 text-emerald-600' },
  { icon: BriefcaseBusiness, title: 'Application tracking', text: 'One calm home for every role, deadline, follow-up, and next step.', tone: 'bg-orange-50 text-orange-600' },
  { icon: Lightbulb, title: 'Career insights', text: 'Understand your market position and the skills that will move you forward.', tone: 'bg-rose-50 text-rose-600' },
  { icon: ShieldCheck, title: 'Built for privacy', text: 'Your profile, preferences, and job-search activity stay in your control.', tone: 'bg-indigo-50 text-indigo-600' },
];

export default function LandingPage() {
  const { openModal } = useContext(ModalContext);
  const start = () => openModal('signup');

  return (
    <div className="bg-white text-slate-900 selection:bg-violet-200">
      <section className="relative overflow-hidden bg-gradient-to-br from-[#fbfcff] via-[#f5f7ff] to-[#f7f3ff]">
        <div aria-hidden className="absolute -right-36 -top-52 h-[32rem] w-[32rem] rounded-full bg-blue-200/30 blur-3xl" />
        <div className="relative mx-auto grid max-w-7xl grid-cols-1 items-center gap-12 px-6 pb-24 pt-20 md:grid-cols-2 md:px-10 md:pb-28 md:pt-28">
          <div>
            <p className="mb-4 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.17em] text-violet-600"><Sparkles className="h-3.5 w-3.5" /> Your career operating system</p>
            <h1 className="max-w-xl font-sans text-5xl font-black leading-[1.06] tracking-[-0.055em] text-slate-950 sm:text-6xl">Find work that feels <span className="bg-gradient-to-r from-violet-600 to-blue-500 bg-clip-text text-transparent">right.</span></h1>
            <p className="mt-6 max-w-xl text-base leading-8 text-slate-500 sm:text-lg">A calmer, smarter job search. CareerCraft turns your skills, goals, and experience into focused opportunities—and helps you make every application count.</p>
            <div className="mt-8 flex flex-wrap gap-3"><button onClick={start} className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-violet-600 to-blue-500 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-violet-300/40 transition hover:-translate-y-0.5 hover:shadow-xl">Start for free <ArrowRight className="h-4 w-4" /></button><a href="#how-it-works" className="rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-bold text-slate-700 shadow-sm transition hover:border-slate-300 hover:bg-slate-50">Explore how it works</a></div>
            <div className="mt-7 flex items-center gap-3 text-xs font-medium text-slate-500"><div className="flex -space-x-2"><span className="h-7 w-7 rounded-full border-2 border-white bg-gradient-to-br from-amber-200 to-rose-400" /><span className="h-7 w-7 rounded-full border-2 border-white bg-gradient-to-br from-teal-200 to-blue-500" /><span className="h-7 w-7 rounded-full border-2 border-white bg-gradient-to-br from-yellow-200 to-orange-400" /></div>Trusted by 50,000+ ambitious professionals</div>
          </div>
          <div className="mx-auto w-full max-w-xl rotate-1 rounded-[22px] border border-slate-200 bg-white p-3 shadow-2xl shadow-slate-400/20 transition duration-500 hover:rotate-0">
            <div className="overflow-hidden rounded-[14px] border border-slate-200 bg-[#fbfcff]"><div className="flex h-9 items-center gap-1.5 border-b border-slate-200 bg-white px-4"><span className="h-2 w-2 rounded-full bg-amber-300" /><span className="h-2 w-2 rounded-full bg-emerald-300" /><span className="h-2 w-2 rounded-full bg-blue-300" /></div><div className="grid min-h-[390px] grid-cols-[105px_1fr]"><aside className="bg-[#13233f] px-3 py-5 text-[10px] text-slate-300"><strong className="mb-7 block text-xs text-white">CareerCraft</strong>{['Overview', 'Jobs', 'Resume', 'Interviews', 'Profile'].map((item, i) => <p key={item} className={`mb-3 rounded-md px-2 py-2 ${i === 0 ? 'bg-white/15 text-white' : ''}`}>{i === 0 ? '⌂' : '◇'}&nbsp; {item}</p>)}</aside><div className="p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="font-bold text-slate-900">Good morning, Maya</h2><p className="mt-1 text-[11px] text-slate-400">Here is your opportunity pulse.</p></div><span className="h-8 w-8 rounded-full bg-gradient-to-br from-amber-200 to-rose-400" /></div><div className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-2"><div className="rounded-xl bg-indigo-50 p-4"><p className="text-[10px] text-slate-500">Career readiness score</p><b className="mt-1 block text-3xl text-slate-900">88 <small className="text-xs font-medium text-slate-400">/ 100</small></b><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-indigo-100"><div className="h-full w-[88%] rounded-full bg-gradient-to-r from-violet-500 to-blue-500" /></div></div><div className="hidden rounded-xl bg-slate-50 p-4 sm:block"><p className="text-[10px] text-slate-500">Profile momentum</p><svg viewBox="0 0 150 60" className="mt-3 h-14 w-full" aria-label="Profile momentum increasing"><path d="M0 50 C16 36 24 44 38 31 S58 38 72 20 S100 29 110 13 S132 22 150 4" fill="none" stroke="#7057e8" strokeWidth="3" /><path d="M0 50 C16 36 24 44 38 31 S58 38 72 20 S100 29 110 13 S132 22 150 4 L150 60 L0 60Z" fill="#7057e818" /></svg></div></div><div className="mt-4 divide-y divide-slate-100">{jobs.map(([letter, role, company, match]) => <div key={role} className="flex items-center gap-2.5 py-2.5"><span className="grid h-7 w-7 place-items-center rounded-lg bg-blue-100 text-[10px] font-bold text-blue-600">{letter}</span><span className="min-w-0 flex-1"><b className="block truncate text-[11px] text-slate-700">{role}</b><small className="block truncate text-[10px] text-slate-400">{company}</small></span><span className="rounded-md bg-emerald-50 px-1.5 py-1 text-[9px] font-bold text-emerald-700">{match}</span></div>)}</div></div></div></div>
          </div>
        </div>
      </section>
      <div className="relative z-10 mx-auto -mt-9 grid max-w-5xl grid-cols-1 divide-y divide-slate-200 rounded-2xl border border-slate-200 bg-white px-8 py-4 shadow-xl shadow-slate-300/20 sm:grid-cols-3 sm:divide-x sm:divide-y-0"><Metric value="50K+" label="professionals supported" /><Metric value="10K" label="fresh jobs every day" /><Metric value="85%" label="get interviews in 30 days" /></div>
      <section id="features" className="mx-auto max-w-7xl px-6 py-28 md:px-10"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.17em] text-violet-600">Less searching. More progress.</p><h2 className="mt-3 text-4xl font-black tracking-[-0.045em] text-slate-950 md:text-5xl">Everything you need for a stronger job search.</h2><p className="mt-4 text-base leading-7 text-slate-500">Thoughtful tools that keep your search organized, your resume relevant, and your confidence high.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{features.map(({ icon: Icon, title, text, tone }) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-7 transition hover:-translate-y-1 hover:border-violet-200 hover:shadow-xl hover:shadow-slate-200/50"><span className={`mb-6 grid h-11 w-11 place-items-center rounded-xl ${tone}`}><Icon className="h-5 w-5" /></span><h3 className="font-bold text-slate-900">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{text}</p></article>)}</div></section>
      <section id="how-it-works" className="bg-slate-50"><div className="mx-auto max-w-7xl px-6 py-28 md:px-10"><div className="max-w-xl"><p className="text-xs font-bold uppercase tracking-[0.17em] text-violet-600">A simpler path forward</p><h2 className="mt-3 text-4xl font-black tracking-[-0.045em] text-slate-950 md:text-5xl">Three steps from looking to landing.</h2></div><div className="mt-14 grid gap-10 md:grid-cols-3">{[['01','Tell us where you are going','Add your experience, strengths, and the kind of work you want to do next.'],['02','Focus on the best fits','CareerCraft surfaces relevant roles and explains why each one is worth your time.'],['03','Apply with confidence','Tailor your materials, prepare for conversations, and stay on top of every opportunity.']].map(([number,title,text], index) => <article key={number} className="relative"><div className={`grid h-14 w-14 place-items-center rounded-full text-sm font-black text-white shadow-lg ${index === 0 ? 'bg-[#13233f]' : index === 1 ? 'bg-violet-600' : 'bg-blue-500'}`}>{number}</div><h3 className="mt-6 text-lg font-bold text-slate-900">{title}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-slate-500">{text}</p></article>)}</div></div></section>
      <section className="px-6 py-24 md:px-10"><div className="relative mx-auto max-w-7xl overflow-hidden rounded-[28px] bg-gradient-to-br from-[#142542] via-[#263e6d] to-violet-600 px-7 py-16 text-white shadow-2xl md:px-16"><div aria-hidden className="absolute -right-16 -top-24 h-80 w-80 rounded-full border-[42px] border-white/10" /><p className="relative text-xs font-bold uppercase tracking-[0.17em] text-violet-200">Your next chapter starts here</p><h2 className="relative mt-3 max-w-2xl text-4xl font-black tracking-[-0.05em] md:text-5xl">Make your job search feel possible again.</h2><p className="relative mt-5 max-w-xl leading-7 text-blue-100">Join people building better careers with clarity, momentum, and a little help from AI.</p><button onClick={start} className="relative mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-800 transition hover:-translate-y-0.5">Create your free account <ArrowRight className="h-4 w-4" /></button></div></section>
    </div>
  );
}

function Metric({ value, label }: { value: string; label: string }) { return <div className="py-3 text-center sm:px-6"><b className="block text-2xl font-black text-slate-900">{value}</b><span className="mt-1 block text-xs text-slate-500">{label}</span></div>; }
