steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE}'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_BASE_URL=${_API}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_FB_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_FB_AUTH}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_FB_PROJ}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_FB_BUCKET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_FB_SENDER}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_FB_APP}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_FB_MEASURE}'
      - '.'
images:
  - '${_IMAGE}'
timeout: '1200s'
